### ISSUE TITLE
Expand/contract nodes programatically

### ISSUE THREAD

**Issue by fjmorant** [fjmorant/react-native-nested-listview#105]

**Comment by TakaKeiji** [comment]
Please considere this scenario:
- Nested list with checkboxes
- Keep checkboxes state using extradata prop
- After extradata state change keep or give an option to keep child nodes expanded

**Comment by fjmorant** [comment]
@TakaKeiji  thx for your notes, I will consider those

**Comment by mallipurna03** [comment]
How can i do this in my application, I need this feature to implement in my app, please suggest me how can i acheive this. Thanks.

**Comment by mallipurna03** [comment]
I have the nested list with 3 levels of the data. What i want to do is, when i tap level 1 items, i want to collapse expanded level 1 items.

**Comment by fjmorant** [comment]
I am going to use Github issues only for issues
