### ISSUE TITLE
Appears to be a git repo or submodule.

### ISSUE THREAD

**Issue by hamid** [fjmorant/react-native-nested-listview#116]
`ERR! git  .../node_modules/react-native-nested-listview: Appears to be a git repo or submodule.`

...
`"react-native-nested-listview": "^0.7.1",`
...

**Comment by fjmorant** [comment]
Hi @hamid ,

Thanks for the feedback is always appreciated, what is the issue when you try to use the library as a dependency in your project you get that error message??

Can you try without the ^?

Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fjmorant** [comment]
@hamid should be fixed in 0.7.2

**Comment by fjmorant** [comment]
This is fixed already
