### ISSUE TITLE
i want dynamic height of row 

### ISSUE THREAD

**Issue by nikunjjaineaton** [fjmorant/react-native-nested-listview#128]
<NestedListView
         style={{ height: '100%',flexGrow: 0 }}
        data={devices}
        getChildrenName={(node) => 'children'}
        onNodePressed={(node) => {alert(node.name)
        console.log(node)}}
        renderNode={(node, level) => (

<NestedRow
      //   height = {0} //this shoud not be hard coded
         level={level}
         style={{ flexGrow:0,borderColor: 'black', borderWidth: 1}}
       >

              <DeviceRow cropType={node.cropType} gpm={node.gpm} name={node.name} status={node.status} />
            
            </NestedRow>

**Comment by fjmorant** [comment]
Hi @nikunjjaineaton ,

Thanks for the suggestion, at the moment, that behaviour is not supported I am afraid but I'll add it in the roadmap


you can create a PR

**Comment by fjmorant** [comment]
Solved
