### ISSUE TITLE
`keepOpenState={true}` no effect

### ISSUE THREAD

**Issue by codthing** [fjmorant/react-native-nested-listview#251]
I try to use keepOpenedState={true} to open the list by default in NestedListView. But to no avail.
![image](https://user-images.githubusercontent.com/16655229/106352495-95e65100-631e-11eb-94f4-77b51c76ae65.png)

>"expo": "~40.0.0",
> "react": "16.13.1",
> "react-dom": "16.13.1",
> "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",

**Comment by fjmorant** [comment]
@mofengfs Do you have an example I could work on? Here in this example you can find that changing the data keeps the state of the nodes opened (obviously if the data is completely new is going to start from being close) https://github.com/fjmorant/react-native-nested-listview-examples/blob/master/DynamicContentExample.js

**Comment by fjmorant** [comment]
This is fixed in the latest version of the library, take into account that if you change completely the data of the list with new one then this library starts the state from the beginning because you've never opened those new nodes
