### ISSUE TITLE
How to judge is the last level, because my data level is not fixed.

### ISSUE THREAD

**Issue by mofengfs** [fjmorant/react-native-nested-listview#252]
I need to do '+' and '-' .  I want to not display '+' / '-'  at the last level.

**Comment by fjmorant** [comment]
I think to do that I would need to expose the number of children per level, let me do it in a new release, thanks for the advice

**Comment by fjmorant** [comment]
@mofengfs added a new arg in renderNode to know if it is the last level or not https://github.com/fjmorant/react-native-nested-listview/pull/256

**Comment by mofengfs** [comment]
@fjmorant 
good job👍
