### ISSUE TITLE
Rendering is slow after onNodePressed

### ISSUE THREAD

**Issue by codthing** [fjmorant/react-native-nested-listview#253]
![image](https://user-images.githubusercontent.com/16655229/106699718-5cfbf400-661e-11eb-81d9-15dfe3d32852.png)

**Comment by fjmorant** [comment]
Hi ,

Thanks for your feedback, I think I know why it is this, soon I will fix this issue and others detected by other users.

Bye

**Comment by fjmorant** [comment]
@mofengfs one potential fix for this would be to use the hook `useCallback`

**Comment by fjmorant** [comment]
Soon I will investigate the issue deeply

**Comment by fjmorant** [comment]
This issue is fixed in the latest version of the library https://github.com/fjmorant/react-native-nested-listview/releases/tag/v0.11.2
