### ISSUE TITLE
Bug when use Nested-listview and Scroll View

### ISSUE THREAD

**Issue by nnhunguet** [fjmorant/react-native-nested-listview#267]
Bug when open 2 NestedRow. 
Invariant Violation: A VirtualizedList contains a cell which itself contains more than one VirtualizedList

https://user-images.githubusercontent.com/52577080/110600859-407d3b00-8139-11eb-9eed-f3c813d0a8d6.mov

![Screen Shot 2021-03-10 at 15 38 29](https://user-images.githubusercontent.com/52577080/110600614-fac07280-8138-11eb-97f9-c345931ec177.png)

**Comment by fjmorant** [comment]
yes, that's expected the way it is implemented the library it is not suppose to have it embedded in a scrollview but I am going to fix that because I am planning to not use FlatList in the app anymore

**Comment by nnhunguet** [comment]
I can't fix this problem, Can you help me ?

**Comment by nnhunguet** [comment]
Problem action when data is immutable, we ussually when use. Thank you !
