### ISSUE TITLE
Bug app

### ISSUE THREAD

**Issue by ps09754** [fjmorant/react-native-nested-listview#272]
"react-native": "^0.62.2",
   react-native-nested-listview : 0.10.0
![1c1302f0b09642c81b87](https://user-images.githubusercontent.com/66257974/112569199-4e5bdd00-8e16-11eb-80b9-c79dbe8afa81.jpg)

**Comment by fjmorant** [comment]
> "react-native": "^0.62.2",
> react-native-nested-listview : 0.10.0
> ![1c1302f0b09642c81b87](https://user-images.githubusercontent.com/66257974/112569199-4e5bdd00-8e16-11eb-80b9-c79dbe8afa81.jpg)

Sorry for the delay in replying, could you send code with the library being used?? thx

**Comment by fjmorant** [comment]
This bug doesn't seem to be related with this library
