### ISSUE TITLE
automatically close list view when setState parent component in v 0.11.3

### ISSUE THREAD

**Issue by nguyenNCphpFox** [fjmorant/react-native-nested-listview#384]
**Describe the bug**
automatically close list view when setState parent component in v 0.11.3
Work good in v 0.11.2
**To Reproduce**
1. Go to ExtraDataExample screen
2. Click on show item 1.2
3. Click check

https://user-images.githubusercontent.com/76427630/155840513-d08e4cc4-f4c7-416f-80cc-dfcc3d35a0ed.mp4

**Comment by fjmorant** [comment]
You are absolutely right, thx for reporting this issue, I will take a look shortly

**Comment by fjmorant** [comment]
Solved in version [0.11.4](https://github.com/fjmorant/react-native-nested-listview/releases/tag/v0.11.4)

**Comment by fjmorant** [comment]
thx, for reporting this I will investigate it and fix it

**Comment by fjmorant** [comment]
0.13.1 solves this issue
