### ISSUE TITLE
Cann't use with state redux

### ISSUE THREAD

**Issue by nguyenNCphpFox** [fjmorant/react-native-nested-listview#386]
**Describe the bug**
When I use data from redux get by useSelector and pass to data NestedListView App crash with issue:
Error: Invariant failed: A state mutation was detected between dispatches, in the path 'photoBoxes.0.childs'
**To Reproduce**
1. `const photoBoxes = useSelector(state => state.photoBoxes)`
2.  <NestedListView
              data={photoBoxes}
              extraData={itemSelected}
              getChildrenName={()=>'childs'}
              renderNode={...}
      />
  3. Update state photoBoxes by action
**Expected behavior**
Don't crash
![Simulator Screen Shot - iPhone 12 - 2022-03-01 at 23 12 34](https://user-images.githubusercontent.com/76427630/156205624-f1ad0b91-0983-4e03-9fba-b7bcead71c38.png)

**Screenshots**

**Comment by fjmorant** [comment]
interesting, the library should work fine with redux too, I am going to create an example in the examples project so that we can have a reference and make sure it always works.

Many thx

**Comment by fjmorant** [comment]
ok, I have created an example for Redux, and it works fine, https://github.com/fjmorant/react-native-nested-listview-examples/blob/master/ReduxExample.tsx, so it would be interesting to know if there un your code there is something else a `useEffect` maybe??

**Comment by fjmorant** [comment]
A potential fix of this issue has been amended in version https://github.com/fjmorant/react-native-nested-listview/releases/tag/v0.11.5, please take a look
