### ISSUE TITLE
Render is slow when there is a lot of data

### ISSUE THREAD

**Issue by sunflowerTB** [fjmorant/react-native-nested-listview#416]
The generateIds function makes rendering very slow when there is a lot of data, need to map all the items. This makes the performance of the app very slow, please consider
Because the video uploaded was 10MB, I shortened the video, the actual loading time was much slower

https://user-images.githubusercontent.com/111519970/185433958-b02a079e-964b-49e3-afbe-73653ebc0833.mov

**Comment by fjmorant** [comment]
ok, let me consider this, how many items are you trying to load?? 

I have an idea in mind to make this more optimal

**Comment by sunflowerTB** [comment]
About 500 items

**Comment by sunflowerTB** [comment]
Hi @fjmorant, have you considered this issue yet?

**Comment by fjmorant** [comment]
I have checked and indeed that function slows down the startup of the component, I have a branch with a version that generates id as it opens nodes on the fly, and works faster but I need to check all cases well

**Comment by sunflowerTB** [comment]
yeah, I'll wait for your bug fix

**Comment by fjmorant** [comment]
Solved in version 0.13.0, thx for your feedback
