### ISSUE TITLE
The listview not refreshed when setState

### ISSUE THREAD

**Issue by dongchuanlei** [fjmorant/react-native-nested-listview#48]
After the network request data is completed, the listview not refreshed when setState. My react native version is 0.50.3

**Comment by fjmorant** [comment]
Hi @dongchuanlei ,

which version are you using? latest master or 0.3.0? thx

**Comment by dongchuanlei** [comment]
I'm using the latest version 0.3.0

**Comment by fjmorant** [comment]
Hi,

So as I understand it you are changing the data prop after a network request and the listview doesn’t refresh, is this correct?

If that’s the case, that is not currently supported, react-native-nested-listview is static but it is in the roadmap and I can prioritise it for helping in your project thx

**Comment by fjmorant** [comment]
Here it is the ticket https://github.com/fjmorant/react-native-nested-listview/issues/24

**Comment by dongchuanlei** [comment]
Yes, that's right.Thank you very much.

**Comment by fjmorant** [comment]
Here there a PR for that change https://github.com/fjmorant/react-native-nested-listview/pull/53

**Comment by fjmorant** [comment]
Published version 0.4.0 which includes this feature
