### ISSUE TITLE
Plans for onChildrenPressed

### ISSUE THREAD

**Issue by efstathiosntonas** [fjmorant/react-native-nested-listview#50]
Thanks for this module, one question, are you planning adding onChildrenPressed method?

**Comment by fjmorant** [comment]
Hi @efstathiosntonas ,

with this method `onNodePressed`you can capture onPress events of any node in the NestedListView, would it be this sufficient?

Thanks

**Comment by efstathiosntonas** [comment]
Let’s assume that we have an app for an e-shop.

—-Category 1
  — Product 1
—- Category 2
  —Product 2

When i click on Category i dont want onPress event, only on Product so i can navigate to products page.

**Comment by fjmorant** [comment]
Hi @efstathiosntonas ,

Ok, now I understand it I think it makes sense to be able to set onNodePressed in the levels you want, I will create a ticket and I will include it in the roadmap. https://github.com/fjmorant/react-native-nested-listview/issues/51

Thanks

**Comment by efstathiosntonas** [comment]
@fjmorant thanks!
