### ISSUE TITLE
add selectedValues and currentValue properties

### ISSUE THREAD

**Issue by violabg** [fjmorant/react-native-nested-listview#63]
it would be nice to have a list of all selected (opened) values of the list as selectedValues
and the last clicked node as currentValue, so that we can give e visual feedback on which node is currently selected.

**Comment by fjmorant** [comment]
Hi @violabg ,

selectedValues is something not supported yet but I will include it in the roadmap.

Regarding currentValue, 

```
<NestedListView
  data={data}
  getChildrenName={(node) => 'items'}
  onNodePressed={(node) => alert('Selected node')}
  renderNode={(node, level) => (
    <NestedRow
      level={level}
      style={styles.row}
    >
      <Text>{node.title}</Text>
    </NestedRow>
  )}
/>
```

`onNodePressed` returns the node, would it be sufficient to cover the use case you were talking about?

Thanks

**Comment by violabg** [comment]
> 

> 

>

**Comment by violabg** [comment]
You are right, my request for currentValue was misleading.  `onNodePressed` is good to track the value of the node, but you can't control the appearance of the other nodes.
What I meant was that each node should have a "`current/selected`" property so that I can give a visual feedback of the selection. 
An example could be a different background color or a check icon, on the last clicked node, this should also deselect the previous clicked node.

**Comment by fjmorant** [comment]
Hi @violabg ,

Thank for the explanation.

One more question, when you say "`current/selected`", are you talking about to know which nodes are opened? if that the case I think is covered in this example https://github.com/fjmorant/react-native-nested-listview/blob/master/examples/StateChangeNodeExample.js

But if you are talking about selecting without opening (select with a checkbox or something like that but not opened the node) I would need to give it a more careful thought.


Thanks

**Comment by violabg** [comment]
you example highlights all the opened nodes, I need to be exclusive. So while I click on a node, should also remove the highlight from the previous.
Basically I need to get only one value from the list, so while you browser the list (open nodes to search for values) at the and you click a "DONE" button the will set the value of the list with the latest clicked node.
I can do that with `onNodePressed`, but I want to give the user a visual feedback of what is currently the latest selection.
whit `onNodePressed` I can highlight the current node, but I can't access the previous node to remove the highlight.

**Comment by fjmorant** [comment]
Ok, yes you are right that behaviour is currently not supported in the library, I will check the API and see how this can be implemented.

THanks for your suggestion.
