### ISSUE TITLE
Accordion like behavior of list

### ISSUE THREAD

**Issue by brystfire08** [fjmorant/react-native-nested-listview#77]
Hello :)

Just want to ask if there is a plan for the nested list view to have an Accordion like behavior. It would be better if there is an option that we can close other list if a list header of it's same level is clicked. If it isn't too much to ask. Thanks.

**Comment by fjmorant** [comment]
Hi @brystfire08 ,

It is a good idea, I will include for the next release.

Thank you very much.

**Comment by mallipurna03** [comment]
I am waiting for this..thanks

**Comment by fjmorant** [comment]
I am going to use Github issues only for issues
