### ISSUE TITLE
List collapses on state (data) change

### ISSUE THREAD

**Issue by adam-nmth** [fjmorant/react-native-nested-listview#92]
Hey,

really neat library you got here! My only problem so far, is when I want to change my data structure via setState(), the whole list collapses, and I have to start opening everything again.

Is there a way to go around this? (I couldn't find any similar cases in the examples, nor the Issues on github.

```javascript
export default class ExampleApp extends React.Component {
  state = {
    currentList: data
  }

  getChildrenName = node => {
    return 'children';
  }

  addItem = () => {
    this.setState({
      currentList: [
        ...this.state.currentList.slice(0, 0), // 2018 year
        {
          ...this.state.currentList[0],
          children: [
            ...this.state.currentList[0].children.slice(0, 0), // oktober first month
            {
              ...this.state.currentList[0].children[0],
              children: [
                ...this.state.currentList[0].children[0].children.slice(0, 0),
                {
                  name: 'SORELEJE'
                },
                ...this.state.currentList[0].children[0].children.slice(1)
              ]
            },
            ...this.state.currentList[0].children.slice(1)
          ]
        },
        ...this.state.currentList.slice(1)
      ]
    })
  }

  renderItem = (node, level) => {
    console.log('Level', level);
    return (
      <View
        style={{ paddingLeft: 12, flexDirection: 'row', alignItems: 'center' }}
      >
        <Text style={{ marginRight: 24 }}>{node.name}</Text>
        {level == 2 && (
          <TouchableOpacity onPress={this.addItem} >
            <Icon name="add" size={30} />
          </TouchableOpacity>
        )}
      </View>
    );
  };

  render() {
    return (
      <View style={styles.container}>
        <NestedListView
          data={this.state.currentList}
          getChildrenName={this.getChildrenName}
          renderNode={(node, level) => (
            <NestedRow
              level={level}
              paddingLeftIncrement={0}
              style={{ borderColor: 'black', borderWidth: 1 }}
            >
              {this.renderItem(node, level)}
            </NestedRow>
          )}
        />
      </View>
    );
  };
}
```

**Comment by fjmorant** [comment]
Hi @adam-nmth ,

Sorry for the delay in replying to your issue.

In your example, you are creating a completely new object (state)  and passing it to the data prop. It is not possible for the moment to pass new data without affecting the open/close state of each node because everything it will be created, I am afraid I don't have an answer now but I will take a look closer and see if I can improve it.

Thanks

**Comment by mfachmirizal** [comment]
well, i got same issue

**Comment by fjmorant** [comment]
Sorry guys, I have been quite busy with other projects and I haven't paid enough attention to this one, soon I am going to focus my attention to this one and this issue is my main priority

**Comment by inctor** [comment]
Hey @fjmorant , is there an ETA on when this can be merged into master to be used for production purposes? :)

**Comment by fjmorant** [comment]
Hi @inctor ,

Sorry for the late response to this issue,  I have been involved in multiple projects. 

The ETA for this PR to be merged in the master is (if there are no delays) in two weeks time and then release a new version of the library (0.9.0)

Bye

**Comment by inctor** [comment]
Hi @fjmorant ,
No worries! We were just in need of a component that does basically all the things this library can do, except for injecting new data elements without collapsing the entire list (or at minimum a way to re-open the specific elements programmatically after updating the list of items it traverses).

I found one other library that can likely do what's required, but the documentation is all in Chinese and is nowhere nearly as recommended as this library is :)

We'll hold out for the two weeks time and hope this fix can solve our requirement :)

Thanks for the good work on the library so far! :)

**Comment by fjmorant** [comment]
Hi,

This is solved already here https://github.com/fjmorant/react-native-nested-listview/pull/241

And also release in version 0.9.0 of the library
